from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import func  
from os import path
from utils import fix_path


db = SQLAlchemy()
sess = db.session

############################################################
#models
############################################################
class c_otu(db.Model):
    __tablename__ = 'otu'

    otu_id = db.Column(db.Integer, primary_key=True)
    lowest_taxonomic_unit_found = db.Column(db.TEXT)

    def __repr__(self):
        return '<c_otu %r>' % (self.name)

		
		
class c_samples_metadata(db.Model):
    __tablename__ = 'samples_metadata'

    SAMPLEID  = db.Column(db.INTEGER, primary_key=True)
    EVENT  = db.Column(db.TEXT)
    ETHNICITY  = db.Column(db.TEXT)
    GENDER  = db.Column(db.TEXT)
    AGE  = db.Column(db.INTEGER)
    WFREQ  = db.Column(db.INTEGER)
    BBTYPE  = db.Column(db.TEXT)
    LOCATION  = db.Column(db.TEXT)
    COUNTRY012  = db.Column(db.TEXT)
    ZIP012  = db.Column(db.INTEGER)
    COUNTRY1319  = db.Column(db.TEXT)
    ZIP1319  = db.Column(db.INTEGER)
    DOG  = db.Column(db.TEXT)
    CAT  = db.Column(db.TEXT)
    IMPSURFACE013  = db.Column(db.INTEGER)
    NPP013  = db.Column(db.FLOAT)
    MMAXTEMP013  = db.Column(db.FLOAT)
    PFC013  = db.Column(db.FLOAT)
    IMPSURFACE1319  = db.Column(db.INTEGER)
    NPP1319  = db.Column(db.FLOAT)
    MMAXTEMP1319  = db.Column(db.FLOAT)
    PFC1319  = db.Column(db.FLOAT)

    def __repr__(self):
        return '<c_samples_metadata %r>' % (self.name)

		
		
class c_samples(db.Model):
    __tablename__ = 'samples'		
		
    otu_id = db.Column(db.Integer, primary_key=True)
    BB_940 = db.Column(db.INTEGER)
    BB_941 = db.Column(db.INTEGER)
    BB_943 = db.Column(db.INTEGER)
    BB_944 = db.Column(db.INTEGER)
    BB_945 = db.Column(db.INTEGER)
    BB_946 = db.Column(db.INTEGER)
    BB_947 = db.Column(db.INTEGER)
    BB_948 = db.Column(db.INTEGER)
    BB_949 = db.Column(db.INTEGER)
    BB_950 = db.Column(db.INTEGER)
    BB_952 = db.Column(db.INTEGER)
    BB_953 = db.Column(db.INTEGER)
    BB_954 = db.Column(db.INTEGER)
    BB_955 = db.Column(db.INTEGER)
    BB_956 = db.Column(db.INTEGER)
    BB_958 = db.Column(db.INTEGER)
    BB_959 = db.Column(db.INTEGER)
    BB_960 = db.Column(db.INTEGER)
    BB_961 = db.Column(db.INTEGER)
    BB_962 = db.Column(db.INTEGER)
    BB_963 = db.Column(db.INTEGER)
    BB_964 = db.Column(db.INTEGER)
    BB_966 = db.Column(db.INTEGER)
    BB_967 = db.Column(db.INTEGER)
    BB_968 = db.Column(db.INTEGER)
    BB_969 = db.Column(db.INTEGER)
    BB_970 = db.Column(db.INTEGER)
    BB_971 = db.Column(db.INTEGER)
    BB_972 = db.Column(db.INTEGER)
    BB_973 = db.Column(db.INTEGER)
    BB_974 = db.Column(db.INTEGER)
    BB_975 = db.Column(db.INTEGER)
    BB_978 = db.Column(db.INTEGER)
    BB_1233 = db.Column(db.INTEGER)
    BB_1234 = db.Column(db.INTEGER)
    BB_1235 = db.Column(db.INTEGER)
    BB_1236 = db.Column(db.INTEGER)
    BB_1237 = db.Column(db.INTEGER)
    BB_1238 = db.Column(db.INTEGER)
    BB_1242 = db.Column(db.INTEGER)
    BB_1243 = db.Column(db.INTEGER)
    BB_1246 = db.Column(db.INTEGER)
    BB_1253 = db.Column(db.INTEGER)
    BB_1254 = db.Column(db.INTEGER)
    BB_1258 = db.Column(db.INTEGER)
    BB_1259 = db.Column(db.INTEGER)
    BB_1260 = db.Column(db.INTEGER)
    BB_1264 = db.Column(db.INTEGER)
    BB_1265 = db.Column(db.INTEGER)
    BB_1273 = db.Column(db.INTEGER)
    BB_1275 = db.Column(db.INTEGER)
    BB_1276 = db.Column(db.INTEGER)
    BB_1277 = db.Column(db.INTEGER)
    BB_1278 = db.Column(db.INTEGER)
    BB_1279 = db.Column(db.INTEGER)
    BB_1280 = db.Column(db.INTEGER)
    BB_1281 = db.Column(db.INTEGER)
    BB_1282 = db.Column(db.INTEGER)
    BB_1283 = db.Column(db.INTEGER)
    BB_1284 = db.Column(db.INTEGER)
    BB_1285 = db.Column(db.INTEGER)
    BB_1286 = db.Column(db.INTEGER)
    BB_1287 = db.Column(db.INTEGER)
    BB_1288 = db.Column(db.INTEGER)
    BB_1289 = db.Column(db.INTEGER)
    BB_1290 = db.Column(db.INTEGER)
    BB_1291 = db.Column(db.INTEGER)
    BB_1292 = db.Column(db.INTEGER)
    BB_1293 = db.Column(db.INTEGER)
    BB_1294 = db.Column(db.INTEGER)
    BB_1295 = db.Column(db.INTEGER)
    BB_1296 = db.Column(db.INTEGER)
    BB_1297 = db.Column(db.INTEGER)
    BB_1298 = db.Column(db.INTEGER)
    BB_1308 = db.Column(db.INTEGER)
    BB_1309 = db.Column(db.INTEGER)
    BB_1310 = db.Column(db.INTEGER)
    BB_1374 = db.Column(db.INTEGER)
    BB_1415 = db.Column(db.INTEGER)
    BB_1439 = db.Column(db.INTEGER)
    BB_1441 = db.Column(db.INTEGER)
    BB_1443 = db.Column(db.INTEGER)
    BB_1486 = db.Column(db.INTEGER)
    BB_1487 = db.Column(db.INTEGER)
    BB_1489 = db.Column(db.INTEGER)
    BB_1490 = db.Column(db.INTEGER)
    BB_1491 = db.Column(db.INTEGER)
    BB_1494 = db.Column(db.INTEGER)
    BB_1495 = db.Column(db.INTEGER)
    BB_1497 = db.Column(db.INTEGER)
    BB_1499 = db.Column(db.INTEGER)
    BB_1500 = db.Column(db.INTEGER)
    BB_1501 = db.Column(db.INTEGER)
    BB_1502 = db.Column(db.INTEGER)
    BB_1503 = db.Column(db.INTEGER)
    BB_1504 = db.Column(db.INTEGER)
    BB_1505 = db.Column(db.INTEGER)
    BB_1506 = db.Column(db.INTEGER)
    BB_1507 = db.Column(db.INTEGER)
    BB_1508 = db.Column(db.INTEGER)
    BB_1510 = db.Column(db.INTEGER)
    BB_1511 = db.Column(db.INTEGER)
    BB_1512 = db.Column(db.INTEGER)
    BB_1513 = db.Column(db.INTEGER)
    BB_1514 = db.Column(db.INTEGER)
    BB_1515 = db.Column(db.INTEGER)
    BB_1516 = db.Column(db.INTEGER)
    BB_1517 = db.Column(db.INTEGER)
    BB_1518 = db.Column(db.INTEGER)
    BB_1519 = db.Column(db.INTEGER)
    BB_1521 = db.Column(db.INTEGER)
    BB_1524 = db.Column(db.INTEGER)
    BB_1526 = db.Column(db.INTEGER)
    BB_1527 = db.Column(db.INTEGER)
    BB_1530 = db.Column(db.INTEGER)
    BB_1531 = db.Column(db.INTEGER)
    BB_1532 = db.Column(db.INTEGER)
    BB_1533 = db.Column(db.INTEGER)
    BB_1534 = db.Column(db.INTEGER)
    BB_1535 = db.Column(db.INTEGER)
    BB_1536 = db.Column(db.INTEGER)
    BB_1537 = db.Column(db.INTEGER)
    BB_1539 = db.Column(db.INTEGER)
    BB_1540 = db.Column(db.INTEGER)
    BB_1541 = db.Column(db.INTEGER)
    BB_1542 = db.Column(db.INTEGER)
    BB_1543 = db.Column(db.INTEGER)
    BB_1544 = db.Column(db.INTEGER)
    BB_1545 = db.Column(db.INTEGER)
    BB_1546 = db.Column(db.INTEGER)
    BB_1547 = db.Column(db.INTEGER)
    BB_1548 = db.Column(db.INTEGER)
    BB_1549 = db.Column(db.INTEGER)
    BB_1550 = db.Column(db.INTEGER)
    BB_1551 = db.Column(db.INTEGER)
    BB_1552 = db.Column(db.INTEGER)
    BB_1553 = db.Column(db.INTEGER)
    BB_1554 = db.Column(db.INTEGER)
    BB_1555 = db.Column(db.INTEGER)
    BB_1556 = db.Column(db.INTEGER)
    BB_1557 = db.Column(db.INTEGER)
    BB_1558 = db.Column(db.INTEGER)
    BB_1561 = db.Column(db.INTEGER)
    BB_1562 = db.Column(db.INTEGER)
    BB_1563 = db.Column(db.INTEGER)
    BB_1564 = db.Column(db.INTEGER)
    BB_1572 = db.Column(db.INTEGER)
    BB_1573 = db.Column(db.INTEGER)
    BB_1574 = db.Column(db.INTEGER)
    BB_1576 = db.Column(db.INTEGER)
    BB_1577 = db.Column(db.INTEGER)
    BB_1581 = db.Column(db.INTEGER)
    BB_1601 = db.Column(db.INTEGER)

    def __repr__(self):
        return '<c_samples %r>' % (self.name)  
		
		
